[app.db]
url = "sqlite:///db/app.test.db"
echo = false

[app.cache]
url = "db/cache.test.json"

[app.excel]
excel_conf_url = "config/batch-1.test.toml"

[app.translate]
# 相对路径
lang_conf_url = "config/lang.test.toml"
dict_url = "config/user_dict.test.toml"
