[app.db]
url = "sqlite:///db/app.dev.db"
echo = false

[app.cache]
url = "db/cache.dev.json"

[app.excel]
excel_conf_url = "config/dev/excels.toml"

[app.translate]
# 相对路径
lang_conf_url = "config/dev/lang.toml"
dict_url = "config/dev/dict.toml"
